-- 02_ligues_departements.sql
-- 13 ligues régionales FFHB (métropole + outre-mer)

INSERT INTO core.ligues (code, nom) VALUES
  ('ARA',  'Auvergne-Rhône-Alpes'),
  ('BFC',  'Bourgogne-Franche-Comté'),
  ('BRE',  'Bretagne'),
  ('CVL',  'Centre-Val de Loire'),
  ('COR',  'Corse'),
  ('GES',  'Grand-Est'),
  ('HDF',  'Hauts-de-France'),
  ('IDF',  'Île-de-France'),
  ('NOR',  'Normandie'),
  ('NAQ',  'Nouvelle-Aquitaine'),
  ('OCC',  'Occitanie'),
  ('PDL',  'Pays de la Loire'),
  ('PACA', 'Provence-Alpes-Côte d''Azur'),
  ('GUA',  'Guadeloupe'),
  ('MAR',  'Martinique'),
  ('GUY',  'Guyane'),
  ('REU',  'La Réunion'),
  ('MAY',  'Mayotte')
ON CONFLICT (code) DO NOTHING;

INSERT INTO core.departements (code, nom, ligue_id) VALUES
  ('01', 'Ain',                          (SELECT id FROM core.ligues WHERE code='ARA')),
  ('02', 'Aisne',                        (SELECT id FROM core.ligues WHERE code='HDF')),
  ('03', 'Allier',                       (SELECT id FROM core.ligues WHERE code='ARA')),
  ('04', 'Alpes-de-Haute-Provence',      (SELECT id FROM core.ligues WHERE code='PACA')),
  ('05', 'Hautes-Alpes',                 (SELECT id FROM core.ligues WHERE code='PACA')),
  ('06', 'Alpes-Maritimes',              (SELECT id FROM core.ligues WHERE code='PACA')),
  ('07', 'Ardèche',                      (SELECT id FROM core.ligues WHERE code='ARA')),
  ('08', 'Ardennes',                     (SELECT id FROM core.ligues WHERE code='GES')),
  ('09', 'Ariège',                       (SELECT id FROM core.ligues WHERE code='OCC')),
  ('10', 'Aube',                         (SELECT id FROM core.ligues WHERE code='GES')),
  ('11', 'Aude',                         (SELECT id FROM core.ligues WHERE code='OCC')),
  ('12', 'Aveyron',                      (SELECT id FROM core.ligues WHERE code='OCC')),
  ('13', 'Bouches-du-Rhône',             (SELECT id FROM core.ligues WHERE code='PACA')),
  ('14', 'Calvados',                     (SELECT id FROM core.ligues WHERE code='NOR')),
  ('15', 'Cantal',                       (SELECT id FROM core.ligues WHERE code='ARA')),
  ('16', 'Charente',                     (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('17', 'Charente-Maritime',            (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('18', 'Cher',                         (SELECT id FROM core.ligues WHERE code='CVL')),
  ('19', 'Corrèze',                      (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('2A','Corse-du-Sud',                  (SELECT id FROM core.ligues WHERE code='COR')),
  ('2B','Haute-Corse',                   (SELECT id FROM core.ligues WHERE code='COR')),
  ('21', 'Côte-d''Or',                   (SELECT id FROM core.ligues WHERE code='BFC')),
  ('22', 'Côtes-d''Armor',               (SELECT id FROM core.ligues WHERE code='BRE')),
  ('23', 'Creuse',                       (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('24', 'Dordogne',                     (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('25', 'Doubs',                        (SELECT id FROM core.ligues WHERE code='BFC')),
  ('26', 'Drôme',                        (SELECT id FROM core.ligues WHERE code='ARA')),
  ('27', 'Eure',                         (SELECT id FROM core.ligues WHERE code='NOR')),
  ('28', 'Eure-et-Loir',                 (SELECT id FROM core.ligues WHERE code='CVL')),
  ('29', 'Finistère',                    (SELECT id FROM core.ligues WHERE code='BRE')),
  ('30', 'Gard',                         (SELECT id FROM core.ligues WHERE code='OCC')),
  ('31', 'Haute-Garonne',                (SELECT id FROM core.ligues WHERE code='OCC')),
  ('32', 'Gers',                         (SELECT id FROM core.ligues WHERE code='OCC')),
  ('33', 'Gironde',                      (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('34', 'Hérault',                      (SELECT id FROM core.ligues WHERE code='OCC')),
  ('35', 'Ille-et-Vilaine',              (SELECT id FROM core.ligues WHERE code='BRE')),
  ('36', 'Indre',                        (SELECT id FROM core.ligues WHERE code='CVL')),
  ('37', 'Indre-et-Loire',               (SELECT id FROM core.ligues WHERE code='CVL')),
  ('38', 'Isère',                        (SELECT id FROM core.ligues WHERE code='ARA')),
  ('39', 'Jura',                         (SELECT id FROM core.ligues WHERE code='BFC')),
  ('40', 'Landes',                       (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('41', 'Loir-et-Cher',                 (SELECT id FROM core.ligues WHERE code='CVL')),
  ('42', 'Loire',                        (SELECT id FROM core.ligues WHERE code='ARA')),
  ('43', 'Haute-Loire',                  (SELECT id FROM core.ligues WHERE code='ARA')),
  ('44', 'Loire-Atlantique',             (SELECT id FROM core.ligues WHERE code='PDL')),
  ('45', 'Loiret',                       (SELECT id FROM core.ligues WHERE code='CVL')),
  ('46', 'Lot',                          (SELECT id FROM core.ligues WHERE code='OCC')),
  ('47', 'Lot-et-Garonne',               (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('48', 'Lozère',                       (SELECT id FROM core.ligues WHERE code='OCC')),
  ('49', 'Maine-et-Loire',               (SELECT id FROM core.ligues WHERE code='PDL')),
  ('50', 'Manche',                       (SELECT id FROM core.ligues WHERE code='NOR')),
  ('51', 'Marne',                        (SELECT id FROM core.ligues WHERE code='GES')),
  ('52', 'Haute-Marne',                  (SELECT id FROM core.ligues WHERE code='GES')),
  ('53', 'Mayenne',                      (SELECT id FROM core.ligues WHERE code='PDL')),
  ('54', 'Meurthe-et-Moselle',           (SELECT id FROM core.ligues WHERE code='GES')),
  ('55', 'Meuse',                        (SELECT id FROM core.ligues WHERE code='GES')),
  ('56', 'Morbihan',                     (SELECT id FROM core.ligues WHERE code='BRE')),
  ('57', 'Moselle',                      (SELECT id FROM core.ligues WHERE code='GES')),
  ('58', 'Nièvre',                       (SELECT id FROM core.ligues WHERE code='BFC')),
  ('59', 'Nord',                         (SELECT id FROM core.ligues WHERE code='HDF')),
  ('60', 'Oise',                         (SELECT id FROM core.ligues WHERE code='HDF')),
  ('61', 'Orne',                         (SELECT id FROM core.ligues WHERE code='NOR')),
  ('62', 'Pas-de-Calais',                (SELECT id FROM core.ligues WHERE code='HDF')),
  ('63', 'Puy-de-Dôme',                  (SELECT id FROM core.ligues WHERE code='ARA')),
  ('64', 'Pyrénées-Atlantiques',         (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('65', 'Hautes-Pyrénées',              (SELECT id FROM core.ligues WHERE code='OCC')),
  ('66', 'Pyrénées-Orientales',          (SELECT id FROM core.ligues WHERE code='OCC')),
  ('67', 'Bas-Rhin',                     (SELECT id FROM core.ligues WHERE code='GES')),
  ('68', 'Haut-Rhin',                    (SELECT id FROM core.ligues WHERE code='GES')),
  ('69', 'Rhône',                        (SELECT id FROM core.ligues WHERE code='ARA')),
  ('70', 'Haute-Saône',                  (SELECT id FROM core.ligues WHERE code='BFC')),
  ('71', 'Saône-et-Loire',               (SELECT id FROM core.ligues WHERE code='BFC')),
  ('72', 'Sarthe',                       (SELECT id FROM core.ligues WHERE code='PDL')),
  ('73', 'Savoie',                       (SELECT id FROM core.ligues WHERE code='ARA')),
  ('74', 'Haute-Savoie',                 (SELECT id FROM core.ligues WHERE code='ARA')),
  ('75', 'Paris',                        (SELECT id FROM core.ligues WHERE code='IDF')),
  ('76', 'Seine-Maritime',               (SELECT id FROM core.ligues WHERE code='NOR')),
  ('77', 'Seine-et-Marne',               (SELECT id FROM core.ligues WHERE code='IDF')),
  ('78', 'Yvelines',                     (SELECT id FROM core.ligues WHERE code='IDF')),
  ('79', 'Deux-Sèvres',                  (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('80', 'Somme',                        (SELECT id FROM core.ligues WHERE code='HDF')),
  ('81', 'Tarn',                         (SELECT id FROM core.ligues WHERE code='OCC')),
  ('82', 'Tarn-et-Garonne',              (SELECT id FROM core.ligues WHERE code='OCC')),
  ('83', 'Var',                          (SELECT id FROM core.ligues WHERE code='PACA')),
  ('84', 'Vaucluse',                     (SELECT id FROM core.ligues WHERE code='PACA')),
  ('85', 'Vendée',                       (SELECT id FROM core.ligues WHERE code='PDL')),
  ('86', 'Vienne',                       (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('87', 'Haute-Vienne',                 (SELECT id FROM core.ligues WHERE code='NAQ')),
  ('88', 'Vosges',                       (SELECT id FROM core.ligues WHERE code='GES')),
  ('89', 'Yonne',                        (SELECT id FROM core.ligues WHERE code='BFC')),
  ('90', 'Territoire de Belfort',        (SELECT id FROM core.ligues WHERE code='BFC')),
  ('91', 'Essonne',                      (SELECT id FROM core.ligues WHERE code='IDF')),
  ('92', 'Hauts-de-Seine',               (SELECT id FROM core.ligues WHERE code='IDF')),
  ('93', 'Seine-Saint-Denis',            (SELECT id FROM core.ligues WHERE code='IDF')),
  ('94', 'Val-de-Marne',                 (SELECT id FROM core.ligues WHERE code='IDF')),
  ('95', 'Val-d''Oise',                  (SELECT id FROM core.ligues WHERE code='IDF')),
  ('971','Guadeloupe',                   (SELECT id FROM core.ligues WHERE code='GUA')),
  ('972','Martinique',                   (SELECT id FROM core.ligues WHERE code='MAR')),
  ('973','Guyane',                       (SELECT id FROM core.ligues WHERE code='GUY')),
  ('974','La Réunion',                   (SELECT id FROM core.ligues WHERE code='REU')),
  ('976','Mayotte',                      (SELECT id FROM core.ligues WHERE code='MAY'))
ON CONFLICT (code) DO NOTHING;
